### ISSUE TITLE
[BUG] - Removing a task fails to stop it from executing

### ISSUE THREAD

**Issue by benderdave** [go-co-op/gocron#120]
### Describe the bug

Removing a task doesn't prevent it from being executed.

### To Reproduce

I may be missing something, but it appears that there is no way to actually remove a task. The following unit test will run 'task' for three seconds, and then remove it, but afterward the task still runs.

```
func TestCron(t *testing.T) {
	sched := gocron.NewScheduler(time.UTC)
	sched.StartAsync()
	i := 0
	task := func() {
		fmt.Printf("task %d\n", i)
		i++
	}
	sched.Every(1).Second().Do(task)
	ch := make(chan bool, 1)
	time.AfterFunc(3*time.Second, func() {
		fmt.Println("removing task")
		sched.Remove(task)
		ch <- true
	})
	<-ch
	time.AfterFunc(3*time.Second, func() {
		// during this 3 seconds, the task will still be run
		ch <- true
	})
	<-ch
}

This appears to be because in scheduler.go:scheduleNextRun, the function passed to AfterFunc always calls scheduleNextRun, without regard to whether the job is still in the scheduler's jobs list. It should check that 'job' is currently in the list before scheduling the next execution. (The same issue occurs when the job is removed by reference or tag.)

```
### Version

v0.5.1

### Expected behavior

Once a periodic job is removed it should not run again.

### Additional context

N/A

**Comment by JohnRoesler** [comment]
Hey @benderdave - this should be fixed on matter. Can you confirm? By this pr  https://github.com/go-co-op/gocron/pull/112

**Comment by benderdave** [comment]
@JohnRoesler thanks for the quick response! Appreciate it. I think #112 is close, but doesn't fix the problem I'm seeing when the job is already running at the time Remove is called. As it stands the timer will be stopped but then a new timer will be created once the job finishes its current run. From the Timer go docs...
 
```
For a timer created with AfterFunc(d, f), if t.Stop returns false, then the timer has already expired and the function f has been started in its own goroutine; Stop does not wait for f to complete before returning. If the caller needs to know whether f is completed, it must coordinate with f explicitly.
```

I just don't see any (easy) way to stop the job from rescheduling itself without checking explicitly to avoid the call at scheduler.go:149.

**Comment by JohnRoesler** [comment]
@benderdave I took your sample code and ran it against current master. I get this output:

```
task 0
task 1
task 2
removing task
```

This looks right to me as the tasks are already scheduled by the time the task is removed. Removing a job does successfully stop the timer. If you add a time.sleep inside the task function, you can force the tasks to print after the job has been removed, but this is due to how the timer after func spins them off into their own go routines.

Per the comment on the timer's stop function - [here](https://pkg.go.dev/time#Timer.Stop)

> For a timer created with AfterFunc(d, f), if t.Stop returns false, then the timer has already expired and the function f has been started in its own goroutine; Stop does not wait for f to complete before returning. If the caller needs to know whether f is completed, it must coordinate with f explicitly.

By this, we don't have a way to cancel the job unless you put something directly in your job, e.g. a context with cancel. With this example code you can cancel your job directly when it's removed:

```golang
func main() {
	sched := gocron.NewScheduler(time.UTC)
	sched.StartAsync()
	i := 0
	task := func(ctx context.Context) {
		now := time.Now()
		for time.Now().Before(now.Add(2 * time.Second)) {
			select {
			case <-ctx.Done():
				return
			default:
				continue
			}
		}
		fmt.Printf("task %d\n", i)
		i++
	}

	ctx, cancel := context.WithCancel(context.Background())
	_, _ = sched.Every(1).Second().Do(task, ctx)
	ch := make(chan bool, 1)

	time.AfterFunc(3*time.Second, func() {
		fmt.Println("removing task")
		sched.Remove(task)
		cancel()
		ch <- true
	})
	<-ch
	time.Sleep(5 * time.Second)
}
```
output:
```
task 0
removing task
```

Overall, I believe this is working as intended. I don't see a good way to implement this cancellation ability generically as we can't decide where in the user's function the cancel would be checked.

**Comment by benderdave** [comment]
@JohnRoesler thanks for the example! I think it helps clarify the issue.

In your example `task` will continue to run, even after the call to sched.Remove. It just keeps its own state and stops printing anything after the timeout (you can see that if you add a print after `'case <-ctx.Done():`). If one were to create and remove millions of such tasks they would continue to run throughout the life of the program, even if the scheduler itself were destroyed.

> Overall, I believe this is working as intended. ...

Maybe I'm misunderstanding the semantics of Remove -- why would a user ever call Remove on a periodically running task if they didn't intend the task to not be run again? Or put another way, would there be any difference from the user's point of view before and after calling Remove on a task?

> ... I don't see a good way to implement this cancellation ability generically as we can't decide where in the user's function the cancel would be checked.

What do you think about adding a check each time the job is about to be run. In scheduler.go instead of scheduleNextRun creating a callback that *always* runs the task...

```
	job.setTimer(time.AfterFunc(durationToNextRun, func() {
		s.run(job)
		s.scheduleNextRun(job)
	}))
```

... it could check that the task is still on the list of valid jobs, something like ...

```
	job.setTimer(time.AfterFunc(durationToNextRun, func() {
                jobStillValid := false
                for _, validJob := range s.Jobs() {
                        if job == validJob {
                                jobStillValid := true
                                break
                        }
                }
                if jobStillValid {
		        s.run(job)
		        s.scheduleNextRun(job)
                }
	}))
```

That seems both generic and semantically correct to me. If the user has removed a task, the next time its timer fires nothing will 
 happen -- the task won't run and won't reschedule itself.

Thanks again for your time!

**Comment by JohnRoesler** [comment]
Ah @benderdave great find - thank you so much for pointing that out. Yes, I think that makes a lot of sense as yes, I would agree removing should stop the job (which is what we thought was happening 😞 .

We have a method that will check if the job is still in the scheduler, `s.jobPresent()`, so that could be called inside the set timer block.

Would you like to open a PR or shall I?

**Comment by benderdave** [comment]
Cool! Go ahead and do it if you don't mind. Thanks!

**Comment by JohnRoesler** [comment]
@benderdave I did some more digging, so when we remove a job from the scheduler, we do call `Stop()` on the job's timer, which would cause the timer to be stopped and any additional runs would not occur. I can see that a log line after `ctx.Done` is called, but not continuously. I modified my previous example, and I get this output:

```
task 0
removing task
2021/02/11 15:10:25 Done
2021/02/11 15:10:25 Done
```

I'm running on the latest release, and with go 1.15.6. Do you get the same output? 

Adding a check to the schedule next run, results in the same output.

```golang
	job.setTimer(time.AfterFunc(durationToNextRun, func() {
		if s.jobPresent(job) {
			s.run(job)
			s.scheduleNextRun(job)
		}
	}))
```

**Comment by benderdave** [comment]
With the latest release I see the behavior you're describing -- once the job is removed no further instances are scheduled. There's a jobPresent check in the main body of scheduleNextRun now (added in 507947a7), so the timer callback doesn't need one. Even in the small window of time between when the timer fires and the next one is set, if the job has been removed it will be caught. Looks great!

**Comment by JohnRoesler** [comment]
@thanhniencung I moved your comment to a discussion -> https://github.com/go-co-op/gocron/discussions/493 please continue to provide info there
