### ISSUE TITLE
[BUG] - Runs task twice

### ISSUE THREAD

**Issue by pandurang90** [go-co-op/gocron#52]
Hi everyone, I am trying to integrate `gocron` in my service. But when I tried to run task it is running it twice.

```golang
package services

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func task() {
	fmt.Println("I am running task.")
}
func main() {
	s1 := gocron.NewScheduler(time.UTC)
	s1.Every(1).Monday().Do(task)
	s1.StartAsync()
        select{}
}
```
```
Output:
I am running task.
I am running task.
```

Is there something that I am missing or is it a bug?

Thanks you very much.

**Comment by pandurang90** [comment]
@Streppel could you help me here?

**Comment by Streppel** [comment]
Absolutely, thanks for bringing it out. Will take a look ASAP!

**Comment by Streppel** [comment]
@pandurang90 just to keep you updated I did some investigations but had to take a field trip this week but I'm back at it now

**Comment by 0x18katyan** [comment]
Getting the same issue.

**Comment by adriendomoison** [comment]
@Streppel Any release date? :) Just want to know if I need to switch to another method temporarily or if the fix will be released this week. Thanks!

**Comment by Streppel** [comment]
@adriendomoison by next week for sure! This week I was pretty busy myself but now we're just finishing up with some month issues that were happening as well, and we'd be good to go.

**Comment by Streppel** [comment]
We merged a PR that addressed this. Everything looks good from my tests; If you guys could give it a try and report back the result here, that would be greatly appreciated. If needed, we can reopen this.

**Comment by jrobin42** [comment]
Hello, this problem still occurs in my program. 
The job looks launched twice **in parallel**, it's quiet rare (but it still occurs sometimes) here is a sample of my code : 

```
package messaging

import (
	"fmt"
	"time"

	"github.com/go-co-op/gocron"
)

func task() {
	fmt.Println("Send message")
}

func scheduleTask() {
	loc, _ := time.LoadLocation("Europe/Paris")
	scheduler := gocron.NewScheduler(loc)
	scheduler.Every(1).Day().At("09:00:00").Do(task())
	scheduler.StartAsync()
}

func main() {
	 scheduleTask()
}
```

Sometimes, this is my output : 
```
Send message
Send message
```

I think I find a way by updating the call to my scheduler : 
```
scheduler.Every(1).Day().At("09:00:00").SingletonMode().Do(task())
```
but it does not resolve the real problem.

Thank you !

**Comment by Streppel** [comment]
@jrobin42 so it happens only sometimes, not always?

**Comment by jrobin42** [comment]
yes, I did not found a pattern to reproduce this bug, it only happens sometimes

**Comment by JohnRoesler** [comment]
[v1.4.0](https://github.com/go-co-op/gocron/releases/tag/v1.4.0) is released with a fix. Please let us know if you continue to see this issue occurring.

**Comment by KnBrBz** [comment]
Hi, reproduced in such a way

	cron := "0 0 * * *"
	loc, err := time.LoadLocation("Local")
	if err != nil {
		err = errors.Wrap(err, funcTitle)
		return
	}
	sheduler := gocron.NewScheduler(loc)
	if _, err = sheduler.Cron(cron).Do(r.SetNextWriter); err != nil {
		err = errors.Wrap(err, funcTitle)
		return
	}
	sheduler.StartAsync()

Using for log rotation, to log files were created, instead of one.

First 20210426_235959.log

	[INFO]: 2021-04-26T23:59:59.955 - See prev log in file logs\20210426_175434.log
	[INFO]: 2021-04-27T00:00:00.005 - See next log in file logs\20210427_000000.log

Second 20210427_000000.log

	[INFO]: 2021-04-27T00:00:00.005 - See prev log in file logs\20210426_235959.log

Builded and runned on Win10.
Using v1.5.0

Case '6 0 * * *' worked correct.

**Comment by Streppel** [comment]
Thanks for the info @KnBrBz. We'll investigate more. This bug specifically happened using "0 0 * * *" cron notation, right?

**Comment by KnBrBz** [comment]
Yes, for now wil use fix suggested by jrobin42.

Using notation `0 0 * * *` in another project for month, but application is working in docker. Sheduler in it creates two job: `0 0 * * *` and `0 1 * * *`. No such problems so far.

**Comment by asmaloney** [comment]
I'm also having this problem when I do the following:

```go
s := gocron.NewScheduler(time.Local)
s.StartAsync()
s.Every(1).Minute().Do(somefunc)
```

`somefunc` is called twice each time.

**Comment by JohnRoesler** [comment]
@asmaloney could you share a bigger example of the code? Where are you running this? When I run it outputs once per minute on a Mac

**Comment by asmaloney** [comment]
Hmmm... yeah, this might be tough. I'm using macOS as well, but running this in a docker container based on `golang:1.16-alpine`.

I've only just started to use gocron, so there isn't any other gocron code executing.

Here's the code with the function:

```go
func initThis() {
	s := gocron.NewScheduler(time.Local)
	s.StartAsync()
	s.Every(1).Minute().Do(someFunc)
}

func someFunc() {
	fmt.Printf("someFunc\n")
}
```

It is running once a minute, but "someFunc" is output twice each time.

Not sure if that helps though...

**Comment by asmaloney** [comment]
My apologies for the noise!

Turns out the thing that was calling `initThis` was being called twice by accident, so I was adding it twice... 

User error. 😊

**Comment by JohnRoesler** [comment]
@asmaloney all good! I've seen and done that before myself 😞  😂

**Comment by artemgavrilov** [comment]
https://github.com/go-co-op/gocron/issues/132#issuecomment-901945604

Hi, faced the same bug in my environment (MacOS + docker).  After some debugging, I found that `time.AfterFunc` on [this](https://github.com/go-co-op/gocron/blob/master/scheduler.go#L187) line triggers few milliseconds before the expected time. It seems that the root of the problem in golang:

- https://github.com/golang/go/issues/45582
- https://github.com/golang/go/issues/27090

**Comment by JohnRoesler** [comment]
@artemgavrilov thanks for digging and finding those issues! I’m going to read up because this is a really interesting bug.

**Comment by tamoyal** [comment]
I am also getting this issue. Something like this:

```
func schedule() {
  s := gocron.NewScheduler(time.UTC)
  // Every 5th minute
  s.Cron("*/5 * * * *").WaitForSchedule().Tag("stuff").Do(func() {
    doSomething()
  })
  s.StartAsync()
}

func doSomething() {
  log.Println("Doing something...")
}
```

Prints "Doing something" twice. I have confirmed the code to schedule only runs once.

**Comment by JohnRoesler** [comment]
I added a Dockerfile to golang/go#45582 that reproduces the issue - let's see if we can get some traction on that issue as this appears to be related to Go itself and not our library.

**Comment by abdurrahman-osman** [comment]
Hi I have same issue with version v1.18, I am scheduling the job 1 time, but it runs twice.

**Comment by dhovang** [comment]
I also have this problem, but only sporadically. Like so:
```
s.Every("5m").Do(func() { ... })
s.StartAsync()
```
About one time out of four, so every 20 min approx, it will run twice. Other times it will run only once.

**Comment by JohnRoesler** [comment]
@dhovang can you share more of your code example? I can't recreate the issue on my side.

**Comment by JohnRoesler** [comment]
Closing, please re-open if you have an example to share that's generating this issue. I am unable to reproduce.

**Comment by leafney** [comment]
Using the latest version currently, I encountered a situation where the execution occurs twice. After multiple tests, I found that the occurrence of execution twice is sporadic, and I am not sure under what circumstances it occurs.

```
Starting server at 0.0.0.0:8881...
{"@timestamp":"2023-10-27T16:43:41.435+08:00","caller":"handler/routes.go:25","content":"--running--","level":"info"}

{"@timestamp":"2023-10-27T16:45:00.000+08:00","caller":"handler/routes.go:25","content":"--running--","level":"info"}
{"@timestamp":"2023-10-27T16:45:00.000+08:00","caller":"handler/routes.go:25","content":"--running--","level":"info"}

{"@timestamp":"2023-10-27T16:48:00.000+08:00","caller":"handler/routes.go:25","content":"--running--","level":"info"}
{"@timestamp":"2023-10-27T16:48:00.000+08:00","caller":"handler/routes.go:25","content":"--running--","level":"info"}
```

my code:
```
      s.
	Cron("*/3 * * * *").
	SingletonMode().
	WaitForSchedule().
	Do(func() {
		logx.Info("--running--")
	})
```

However, when I switched to a lower version for testing, I found that the execution twice situation did not occur.

```
require(
        //github.com/go-co-op/gocron v1.35.2 // indirect
        github.com/go-co-op/gocron v1.16.3
)
```
