### ISSUE TITLE
[BUG] - schedule job at specific time

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [go-co-op/gocron#98]
### Describe the bug

I start a scheduler in my local timezone. Then I read the scheduled jobs from a struct in settings.
I receive the start time as a json timestamp, which is converted to a Golang Time. In the printed output, it seems like this conversion works the way it should.

Also when I ask when the next scheduled job is going to run, I see the correct time.

Alas, when the time comes to run the job, nothing happens.

If I add a recurring job to the queue, say every 2 seconds, I do see the function getting executed with the parameters that were passed.

I also see the tag, I added to the job.

Any idea what I might be doing wrong?

Jo

### To Reproduce

`

func main() {
	location, _ := time.LoadLocation("Europe/Brussels")
	scheduler := gocron.NewScheduler(location)

	for _, task := range settings.Schedule {
		PrettyPrint(task)
		now := nowFormatted()
		if task.StartDate > now {
			var DateRE = regexp.MustCompile(`/Date\((?P<UnixTimestamp>\d+)(?P<TZOffset>[-\+]\d+)\)`)
			tsString := DateRE.FindStringSubmatch(task.StartDate)[1]
			timestamp, _ := strconv.ParseInt(tsString, 10, 64)
			startTime := time.Unix(timestamp/1000, 0)
			job, err := scheduler.Every(1).Day().StartAt(startTime).SetTag([]string{task.ID}).Do(taskWithParams, task)
			// scheduler.Every(2).Seconds().Do(taskWithParams, task)
			PrettyPrint(tsString)
			PrettyPrint(timestamp)
			PrettyPrint(startTime.Format("Mon Jan 2 15:04:05 -0700 MST 2006"))
			_, tt := scheduler.NextRun()
			log.Warn("Next run")
			PrettyPrint(tt.Format("Mon Jan 2 15:04:05 -0700 MST 2006"))
			if err != nil {
				log.Error(err)
			}
			if task.RecurrencePattern == "" {
				job.LimitRunsTo(1)
				job.RemoveAfterLastRun()
			}
	scheduler.StartAsync()
}

`
Output:

`
{
  "Action": 0,
  "EndDate": "/Date(1608919200000+0100)/",
  "Filename": "/home/pi/doSomethingImportant.sh",
  "Id": "8a102123-a91d-474b-8f83-547c9cdcf3ad",
  "Parameters": "",
  "ProcedureName": "main",
  "RecurrencePattern": "",
  "ScheduleType": 0,
  "StartDate": "/Date(1608918720000+0100)/"
}
"1608918720000"
1608918720000
"Fri Dec 25 18:52:00 +0100 CET 2020"
WARN[25/12/2020 18:50:35] Next run
"Fri Dec 25 18:52:00 +0100 CET 2020"
[
  "8a102123-a91d-474b-8f83-547c9cdcf3ad"
]
`

**Comment by JohnRoesler** [comment]
Hi Jo, I did some testing with the `StartAt` func locally and it works as expected for me. For example, a simple run:

```
func main() {
	s := gocron.NewScheduler(time.Local)

	s.Every(1).Day().StartAt(time.Now().Add(time.Second * 5)).Do(func() { fmt.Println("hello") })
	s.StartAsync()
	time.Sleep(6 * time.Second)
}
```

Nothing in your code snippet is standing out to me as causing an issue. How are you running this? Possible the host time isn't right in some way that is effecting your application? We had an odd bug a while back where one of the docker containers had a bug in it's timezones that was causing issues (could be unrelated, but made me think of this instance).

**Comment by PolyglotOpenstreetmap** [comment]
I'm also thinking it might be timezone related, so I added a job for an hour later as well.

The reason I was looking into gocron was because I needed 1 second resolution instead of 1 minute. Now I'm experimenting with systemd jobs. In the end I want to start a shell script that starts cvlc or chromium-browser in kiosk mode, so that may be a better fit.

Jo

**Comment by jwzl** [comment]
I has same problem!

**Comment by jwzl** [comment]
s := gocron.NewScheduler(time.Local)
	klog.Infof("%v", s.Location())

	t := time.Date(2021, time.January, 12, 13, 44, 10, 10, time.Local)
	t = time.Now().Add(time.Second * 5)
	job, _ := s.Every(1).Day().StartAt(t).Do(fuck, 8, 9 , 10 , "1221")
	klog.Infof("%v", job.ScheduledAtTime())

	s.Every(1).Day().StartAt(time.Now().In(s.Location()).Add(time.Second * 5)).Do(func() { klog.Infof("hello XXXX") })

these function fuck and func() { klog.Infof("hello XXXX") never reached.

**Comment by jwzl** [comment]
my platform is ubuntu 16.04 amd64

**Comment by jwzl** [comment]
`func (s *Scheduler) scheduleNextRun(job *Job) {
	now := s.now()
	lastRun := job.LastRun()

	// job can be scheduled with .StartAt()
	if job.neverRan() {
		if !job.NextRun().IsZero() {
			return // scheduled for future run and should skip scheduling
		}
		lastRun = now
	}

	durationToNextRun := s.durationToNextRun(lastRun, job)
	job.setNextRun(lastRun.Add(durationToNextRun))
	job.setTimer(time.AfterFunc(durationToNextRun, func() {
		s.run(job)
		s.scheduleNextRun(job)
	}))
}
`
I think it can be return in scheduleNextRun() 
if !job.NextRun().IsZero() {
			return // scheduled for future run and should skip scheduling
		}

**Comment by mikhailbolshakov** [comment]
hi all,
same issue



	s := gocron.NewScheduler(time.Local)

	expectedTime := time.Now().Add(time.Second * 10)
	fmt.Println("expectedTime = ", expectedTime)

	j, _ := s.Every(1).Day().StartAt(expectedTime).Do(func() { fmt.Println("hello") })
	fmt.Println("next run = ", j.NextRun())

	s.StartAsync()

	select {
		case <-time.After(time.Second * 20):
			fmt.Println("time out")
	}


output:
expectedTime =  2021-01-13 13:19:04.831003856 +0300 MSK m=+10.000311079
next run =  2021-01-13 13:19:04.831003856 +0300 MSK m=+10.000311079
time out

Experimenting with timezone gave nothing.

**Comment by JohnRoesler** [comment]
Hi all - looks like a problem with release `v0.5.0` - we'll dig into the bug. Could you try using `v0.4.0` for now and see if that resolves the issue?

**Comment by mikhailbolshakov** [comment]
it works on v0.4.0

**Comment by JohnRoesler** [comment]
@mikhailbolshakov thanks for the confirmation - and for calling out the bug

**Comment by mikhailbolshakov** [comment]
In v0.4.0 we get to the scheduleNextRun after chan ticker is fired,


![cron_debug_v040_0](https://user-images.githubusercontent.com/63634283/104479228-3d038280-55d4-11eb-9b11-6cbe06e6060b.png)

![cron_debug_v040_1](https://user-images.githubusercontent.com/63634283/104479220-3aa12880-55d4-11eb-8807-5df90ebfda8d.png)


 seems in v0.5.0 we don't have such logic at all

![cron_debug_v050](https://user-images.githubusercontent.com/63634283/104478927-e7c77100-55d3-11eb-865e-3afca87447d0.png)

**Comment by JohnRoesler** [comment]
Check out [v0.5.1](https://github.com/go-co-op/gocron/releases/tag/v0.5.1) - this should fix the bug. Thanks again for reporting it!

**Comment by jwzl** [comment]
Thank you very much!@JohnRoesler

**Comment by dlaweb** [comment]
Still have some issue with the 0.5.1
Infinite loop of task with this code:

func task() {
	fmt.Println("Im a dummy task")
	return
}

func main() {
	s1 := gocron.NewScheduler(time.UTC)

	// scheduler starts running jobs and current thread continues to execute
	s1.StartAsync()

	// Remove a Job after its last execution
	j, _ := s1.Every(1).StartAt(time.Now().Add(5 * time.Second)).Do(task)
	j.LimitRunsTo(1)
	time.Sleep(15 * time.Second)
}

**Comment by JohnRoesler** [comment]
@dlaweb this is fixed in #114 

Please confirm when you have a moment!

**Comment by dlaweb** [comment]
@JohnRoesler  Yes it works now, thank you ! 👍

**Comment by arunsybex** [comment]
@dlaweb I'm facing the same issue with v1.31.0

**Comment by JohnRoesler** [comment]
@arunsybex too much has changed for me to believe this is the same issue. Please open a new issue and describe the bug along with a reproducible example (if possible) so that I can dig into the issue you're seeing.
